In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('/home/timur/HM_course/HM3/all_v2.csv')

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5477006 entries, 0 to 5477005
Data columns (total 7 columns):
 #   Column        Dtype
---  ------        -----
 0   price         int64
 1   region        int64
 2   level         int64
 3   levels        int64
 4   rooms         int64
 5   area          float64
 6   kitchen_area  float64
dtypes: float64(2), int64(5)
memory usage: 292.5 MB

In [3]:
data.drop(['building_type', 'date', 'time', 'geo_lon', 'geo_lat', 'object_type'], axis= 1 , inplace= True )

In [6]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split, GridSearchCV

In [18]:
data = data.loc[data['price'] > 100000]
data = data.loc[data['region'] <= 85]
data = data.loc[data['price'] < 1000000000]
data = data.sample(frac=0.25)

In [19]:
data['price'].count()

234828

In [20]:
X = data.drop('price', axis=1)
y = data['price']

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)

In [22]:
rf = RandomForestRegressor()

In [23]:
rf.fit(X, y)

RandomForestRegressor()

In [24]:
rf.score(X_test, y_test)

0.9594339190598042

In [ ]:
rf.predict(np.array([77, 15, 15, 4, 130, 20]).reshape(1, -1))

In [ ]:
np.array([39, 4, 5, 2, 32, 6]).reshape(-1, 1)

In [25]:
import joblib

# Save to file in the current working directory
joblib_file = "joblib_model.pkl"
joblib.dump(rf, joblib_file)

['joblib_model.pkl']

In [40]:
rf.predict(pd.Series([77, 15, 15, 4, 130, 20], ['region', 'level', 'levels', 'rooms', 'area', 'kitchen_area']))

/home/timur/.cache/pypoetry/virtualenvs/homeworkproject-hN4QtuxE-py3.10/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

ValueError: Expected 2D array, got 1D array instead:
array=[ 77.  15.  15.   4. 130.  20.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [51]:
d = {'region': 39, 'level': 3, 'levels': 5, 'rooms': 2, 'area': 50.0, 'kitchen_area': 10.0}
pd.DataFrame(data=d, index=[0])

   region  level  levels  rooms  area  kitchen_area
0      39      3       5      2  50.0          10.0

In [42]:
X_test

         region  level  levels  rooms   area  kitchen_area
5180760      81      6      17      2   50.0          10.0
228979       81      2       9      1   34.0           7.5
1118025      81      4       7      1   32.1           9.0
4634147      81     10      16      3   67.0           8.0
2682816       3     15      17      2   69.1          15.2
...         ...    ...     ...    ...    ...           ...
2335721       3      1       5      1   33.0           6.5
5047360       3     23      30      4  184.0          20.8
856736        3      6      14      3   82.4          11.7
5317823       3     28      32      2   38.2           6.2
3788736      81      1       9      3   72.0           7.0

[117414 rows x 6 columns]